---
- name: Configure firewalld for LDAP auto server
  become: true
  loop: "{{ duoap_ldap_auto_servers }}"
  ansible.posix.firewalld:
    port: "{{ item.ssl_port | default('636') }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Configure firewalld for RADIUS auto server
  become: true
  loop: "{{ duoap_radius_auto_servers }}"
  ansible.posix.firewalld:
    port: "{{ item.port | default('1812') }}/udp"
    permanent: true
    immediate: true
    state: enabled
