---
- name: Reload systemd services
  listen: _duoap_systemd_reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Duo Authentication Proxy service
  listen: _duoap_restart_duoap
  become: true
  ansible.builtin.systemd_service:
    name: duoauthproxy.service
    state: restarted
